### ISSUE TITLE
fix CTD despiking

### ISSUE THREAD

**Issue by thinf** [NPIOcean/kval#8]
Need to get back data selection cursor after zooming and panning in manual ctd-despiking function.

**Comment by oyvfoss** [comment]
Thanks. The cursor can be regained by clicking the zoom/move icon again - I see how that is confusing if you don't already know. 

I added the following text to the displayed plot: `Click icons on right side of the plot to zoom/move/save (click again to regain cursor). ` 

(Changes made in `data.ship.ctd_tools_._ctd_edit` -> `hand_remove_points`)
